import type { GroupReaction } from './group.types.js';

/** A single prior turn sent so the backend has within-thread context. */
export interface ChatHistoryItem {
  role: 'user' | 'assistant';
  text: string;
}

export interface ChatRequest {
  message: string;
  threadId?: string;
  model?: string;
  /**
   * Optional image attached to this turn, as a base64 data URL
   * (e.g. `data:image/png;base64,...`). One image per turn (VIS-01).
   * Only the vision dino's model reasons about it natively; other dinos
   * fall back to a vision-capable model server-side.
   */
  imageDataUrl?: string;
  /** Tool names the user has enabled. Undefined = all available tools. */
  enabledTools?: string[];
  /** Selected dino. When present, backend resolves model + system prompt + tools from it. */
  dinoId?: string;
  /** Anonymous per-device user id (localStorage). Scopes cross-thread memory per (userId × dinoId). */
  userId?: string;
  /** Recent prior turns (capped) so multi-turn follow-ups have context. */
  history?: ChatHistoryItem[];
}

export interface ToolInfo {
  name: string;
  label: string;
  description: string;
}

export interface ToolCallRecord {
  name: string;
  args: Record<string, unknown>;
  result: string;
}

export interface ChatResponse {
  response: string;
  toolCalls?: ToolCallRecord[];
}

export type MessageRole = 'user' | 'assistant' | 'error' | 'tool';

export interface ChatMessage {
  text: string;
  role: MessageRole;
  /** Image the user attached to this turn (base64 data URL), rendered inline (VIS-01). */
  imageDataUrl?: string;
  toolName?: string;
  toolArgs?: Record<string, unknown>;
  toolResult?: string;
  reasoning?: string;
  reasoningDurationMs?: number;
  createdAt?: number;
  /**
   * Group-thread attribution (D-08): the dino that spoke this message in a
   * persisted group transcript. Present on `role === 'assistant'` rows that
   * originated from a group dino; absent for single-dino chats.
   */
  dinoId?: string;
  /**
   * Group-thread attribution (D-08): emoji reactions pinned to this message in
   * a persisted group transcript, so a saved group chat round-trips its chips.
   */
  reactions?: GroupReaction[];
}

export interface ConversationSession {
  id: string;
  title: string;
  messages: ChatMessage[];
  createdAt: number;
  pinned?: boolean;
  /** The dino bound to this session; sent as dinoId on every message. */
  dinoId?: string;
  /** True when this session is a persisted group thread (D-08). */
  isGroup?: boolean;
  /** Saved participant roster for a group thread, so it reopens with the exact dino set (D-08). */
  participantDinoIds?: string[];
}

export interface StreamTokenEvent {
  type: 'token';
  text: string;
}

export interface StreamToolCallStartEvent {
  type: 'tool_call_start';
  id: string;
  name: string;
  args: Record<string, unknown>;
}

export interface StreamToolCallResultEvent {
  type: 'tool_call_result';
  id: string;
  result: string;
}

export interface StreamReasoningTokenEvent {
  type: 'reasoning_token';
  text: string;
}

export interface StreamDoneEvent {
  type: 'done';
  response: string;
  toolCalls?: ToolCallRecord[];
  reasoning?: string;
  reasoningDurationMs?: number;
}

export interface StreamErrorEvent {
  type: 'error';
  message: string;
  link?: string;
}

/** An image generated by an artist dino (base64 data URL), rendered inline (IMG-01/02). */
export interface StreamImageEvent {
  type: 'image';
  imageDataUrl: string;
}

export type StreamEvent =
  | StreamTokenEvent
  | StreamReasoningTokenEvent
  | StreamToolCallStartEvent
  | StreamToolCallResultEvent
  | StreamImageEvent
  | StreamDoneEvent
  | StreamErrorEvent;
