version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    restart: unless-stopped
